### ISSUE TITLE
help with assignment #10 yaml

### ISSUE THREAD

**Issue by trophyDev** [mmumshad/kubernetes-training-answers#2]
this is my answer, what am i doing wrong?

` Employee:
  Name: Jacob
  Sex: Male
  Age: 30
  Title: Systems Engineer
  Projects:
    - Automation
    - Support
    
  Payslips:
    - Month: June
    - Wage:  4000
    - Month: July
    - Wage:  4500
    - Month: August
    - Wage:  4000
`

**Comment by vvelikodny** [comment]
@trophyDev issue at our solution is **Payslips**. It should be a list of dictionaries. Please, look at the `Introduction to YAML` lecture carefully how @mmumshad describe car properties about 6 min.

bwt, answer here
https://github.com/mmumshad/kubernetes-training-answers/blob/master/Section_YAML/Exercise_6/employee.yml

**Comment by trophyDev** [comment]
thank you, I got it
